package it.polimi.ingsw.enumerations;

public enum GameState {

    WELCOME_FIRST, WELCOME, CARD_CHOICE, SET_WORKER,
    WORKER_CHOICE, ACTION,
    QUESTION_PROMETHEUS, PREBUILD_PROMETHEUS,
    MOVEMENT,
    QUESTION_ARTEMIS, SECOND_MOVE,
    QUESTION_ATLAS, CONSTRUCTION_CUPOLA,
    QUESTION_HEPHAESTUS, DOUBLE_CONSTRUCTION,
    QUESTION_DEMETER, SECOND_CONSTRUCTION,
    CONSTRUCTION

}
