package it.polimi.ingsw.network.message;

public enum GameState {

    LOAD_STATE, WELCOME_FIRST, WAIT,
    CARD_CHOICE, SET_WORKER1, SET_WORKER2,
    WELCOME_FIRST,
    WAIT, WAIT_PLAYERS,
    CARD_CHOICE, SET_WORKER,
    WORKER_CHOICE,
    QUESTION_PROMETHEUS, PREBUILD_PROMETHEUS,
    MOVEMENT,
    QUESTION_ARTEMIS, SECOND_MOVE,
    QUESTION_ATLAS, CONSTRUCTION_CUPOLA,
    QUESTION_HEPHAESTUS, DOUBLE_CONSTRUCTION,
    QUESTION_DEMETER, SECOND_CONSTRUCTION,
    CONSTRUCTION

}
